### ISSUE TITLE
DB migration error

### ISSUE THREAD

**Issue by thammerl** [mcallistersean/b2-issue-tracker#44]
```
$ ./manage.py migrate
Operations to perform:
  Apply all migrations: account, admin, auth, contenttypes, invitations, issues, organisations, sessions, site_config, sites, socialaccount, user_profile
Running migrations:
  Applying site_config.0004_auto_20160701_1714...Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/thomas/workspaces/beetwo/b2-issue-tracker/b2it/lib/python3.5/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/home/thomas/workspaces/beetwo/b2-issue-tracker/b2it/lib/python3.5/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/thomas/workspaces/beetwo/b2-issue-tracker/b2it/lib/python3.5/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/thomas/workspaces/beetwo/b2-issue-tracker/b2it/lib/python3.5/site-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/home/thomas/workspaces/beetwo/b2-issue-tracker/b2it/lib/python3.5/site-packages/django/core/management/commands/migrate.py", line 204, in handle
    fake_initial=fake_initial,
  File "/home/thomas/workspaces/beetwo/b2-issue-tracker/b2it/lib/python3.5/site-packages/django/db/migrations/executor.py", line 115, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/home/thomas/workspaces/beetwo/b2-issue-tracker/b2it/lib/python3.5/site-packages/django/db/migrations/executor.py", line 145, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/home/thomas/workspaces/beetwo/b2-issue-tracker/b2it/lib/python3.5/site-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/home/thomas/workspaces/beetwo/b2-issue-tracker/b2it/lib/python3.5/site-packages/django/db/migrations/migration.py", line 129, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/home/thomas/workspaces/beetwo/b2-issue-tracker/b2it/lib/python3.5/site-packages/django/db/migrations/operations/special.py", line 189, in database_forwards
    self.code(from_state.apps, schema_editor)
  File "/home/thomas/workspaces/beetwo/b2-issue-tracker/site_config/migrations/0004_auto_20160701_1714.py", line 14, in create_site_configs
    create_site_config(instance=s)
  File "/home/thomas/workspaces/beetwo/b2-issue-tracker/site_config/signals.py", line 17, in create_site_config
    'issue_point': DEFAULT_POINT
  File "/home/thomas/workspaces/beetwo/b2-issue-tracker/b2it/lib/python3.5/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/thomas/workspaces/beetwo/b2-issue-tracker/b2it/lib/python3.5/site-packages/django/db/models/query.py", line 473, in get_or_create
    return self.get(**lookup), False
  File "/home/thomas/workspaces/beetwo/b2-issue-tracker/b2it/lib/python3.5/site-packages/django/db/models/query.py", line 376, in get
    clone = self.filter(*args, **kwargs)
  File "/home/thomas/workspaces/beetwo/b2-issue-tracker/b2it/lib/python3.5/site-packages/django/db/models/query.py", line 796, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/home/thomas/workspaces/beetwo/b2-issue-tracker/b2it/lib/python3.5/site-packages/django/db/models/query.py", line 814, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/home/thomas/workspaces/beetwo/b2-issue-tracker/b2it/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1227, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/thomas/workspaces/beetwo/b2-issue-tracker/b2it/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1253, in _add_q
    allow_joins=allow_joins, split_subq=split_subq,
  File "/home/thomas/workspaces/beetwo/b2-issue-tracker/b2it/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1158, in build_filter
    self.check_related_objects(field, value, opts)
  File "/home/thomas/workspaces/beetwo/b2-issue-tracker/b2it/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1055, in check_related_objects
    self.check_query_object_type(value, opts, field)
  File "/home/thomas/workspaces/beetwo/b2-issue-tracker/b2it/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1039, in check_query_object_type
    (value, opts.object_name))
ValueError: Cannot query "Site object": Must be "Site" instance.
```

**Comment by mcallistersean** [comment]
The offending code has been removed in an attempt to simplify site handling.
